const songs = [
    {src: "songs/EKSKLUZYWNY_GŁÓD.mp3", title: "EKSKLUZYWNY GŁÓD", artist: "Young igi"},
    {src: "songs/Słup.mp3", title: "Słup", artist: "Białas"},
    {src: "songs/Polsilver.mp3", title: "Polsilver", artist: "PRO8L3M"},
    {src: "songs/Symetryczno-liryczna.mp3", title: "Symetryczno-liryczna", artist: "Enej"},
    {src: "songs/Lili.mp3", title: "Lili", artist: "Enej"},
    {src: "songs/chłopaki jak my.mp3", title: "chłopaki jak my", artist: "Kuban,Favst,Kizo"},
    {src: "songs/Może Będzie lepiej.mp3", title: "Może Będzie lepiej", artist: "Enej"},
    {src: "songs/Skrzydlate ręce.mp3", title: "Skrzydlate ręce", artist: "Kuban,Favst,Kizo"},
    {src: "songs/Nie Chcę Spać.mp3", title: "Nie Chcę Spać", artist: "Enej"},
    {src: "songs/Kamień z Napisem LOVE.mp3", title: "Kamień z Napisem LOVE", artist: "Enej"},
    {src: "songs/Zbudujemy dom.mp3", title: "Zbudujemy dom", artist: "Enej"},
    {src: "songs/Brokeboy.mp3", title: "Brokeboy", artist: "Białas,Szpaku,Tomb"},
    {src: "songs/Uzi.mp3", title: "Uzi", artist: "Białas,Sobel,Deemz"},
    {src: "songs/Nie dla Ciebie.mp3", title: "Nie dla Ciebie", artist: "Solar, Białas, Wac Toja"},
    {src: "songs/GODZILLA FREAKSTYLE.mp3", title: "GODZILLA FREAKSTYLE", artist: "Białas,Lanek"},
    {src: "songs/NIEBIESKI DOM.mp3", title: "NIEBIESKI DOM", artist: "Białas,Lanek"},
    {src: "songs/Intercontinental bajers.mp3", title: "Intercontinental bajers", artist: "Solar, Białas"},
    {src: "songs/Grill u Gawrona.mp3", title: "Grill u Gawrona", artist: "Białas,Lanek"},
    {src: "songs/RED BULL 64 BARS.mp3", title: "RED BULL 64 BARS", artist: "Białas,Sobel,Deemz"},
    {src: "songs/Zosia.mp3", title: "Zosia", artist: "Białas"},
    {src: "songs/Idę na plaże.mp3", title: "Idę na plaże", artist: "Video"},
    {src: "songs/Wszystko Jedno.mp3", title: "Wszystko Jedno", artist: "Video"},
    {src: "songs/Sępy.mp3", title: "Sępy", artist: "Białas,Szpaku"},
    {src: "songs/Jeden żyć.mp3", title: "Jeden żyć", artist: "Białas"},
    {src: "songs/Smutne miasteczko.mp3", title: "Smutne miasteczko", artist: "Białas,Szpaku,Deemz"},
    {src: "songs/Nowy biggie.mp3", title: "Nowy biggie", artist: "Białas"},
    {src: "songs/I poszedł.mp3", title: "I poszedł", artist: "Białas"},
    {src: "songs/Cyka blyat.mp3", title: "Cyka blyat", artist: "Białas,Lanek"},
    {src: "songs/NIE BOJĘ SIĘ DUCHÓW.mp3", title: "NIE BOJĘ SIĘ DUCHÓW", artist: "Białas,Lanek"},
    {src: "songs/Polack.mp3", title: "Polack", artist: "Białas,Lanek"},
    {src: "songs/IGA ŚWIĄTEK VS FAGATA.mp3", title: "IGA ŚWIĄTEK VS FAGATA", artist: "Białas,Lanek"},
    {src: "songs/W Imię Ojca Trapu.mp3", title: "W Imię Ojca Trapu", artist: "Białas,Lanek"},
    {src: "songs/Yokohoma.mp3", title: "Yokohoma", artist: "PRO8L3M"},
    {src: "songs/Otchłań.mp3", title: "Otchłań", artist: "PRO8L3M"},
    {src: "songs/Mayday.mp3", title: "Mayday", artist: "PRO8L3M"},
    {src: "songs/Skansen.mp3", title: "Skansen", artist: "PRO8L3M"},
    {src: "songs/Negroni.mp3", title: "Negroni", artist: "PRO8L3M"},
    {src: "songs/Ground Zero.mp3", title: "Ground Zero", artist: "PRO8L3M"},
    {src: "songs/Molly.mp3", title: "Molly", artist: "PRO8L3M"},
    {src: "songs/Flary.mp3", title: "Flary", artist: "PRO8L3M"},
    {src: "songs/Przebój nocy.mp3", title: "Przebój nocy", artist: "PRO8L3M, Wanda i Banda"},
    {src: "songs/Skrable.mp3", title: "Skrable", artist: "PRO8L3M"},
    {src: "songs/Interpol.mp3", title: "Interpol", artist: "PRO8L3M"},
    {src: "songs/Crash test.mp3", title: "Crash test", artist: "PRO8L3M"},
    {src: "songs/Byłem człowiekiem.mp3", title: "Byłem człowiekiem", artist: "PRO8L3M"},
    {src: "songs/Zadzwoń do mnie.mp3", title: "Zadzwoń do mnie", artist: "PRO8L3M"},
    {src: "songs/Makijaż.mp3", title: "Makijaż", artist: "PRO8L3M"},
    {src: "songs/Freon.mp3", title: "Freon", artist: "PRO8L3M"},
    {src: "songs/Nicea.mp3", title: "Nicea", artist: "PRO8L3M"},
    {src: "songs/młody gandolfini.mp3", title: "młody gandolfini", artist: "Kuban,Favst"},
    {src: "songs/różnie to było.mp3", title: "różnie to było", artist: "Kuban,Favst, Pezet"},
    {src: "songs/najlepszy dzień.mp3", title: "najlepszy dzień", artist: "Kuban,Favst, OKI"},
    {src: "songs/koto freestyle.mp3", title: "koto freestyle", artist: "Kuban,Favst"},
    {src: "songs/nad ranem.mp3", title: "nad ranem", artist: "Kuban,Favst"},
    {src: "songs/budzi mnie wiatr.mp3", title: "budzi mnie wiatr", artist: "Kuban,Favst, Edyta Bartosiewicz"},
    {src: "songs/magister sztuki.mp3", title: "magister sztuki", artist: "Kuban,Favst"},
    {src: "songs/mój kumplu.mp3", title: "mój kumplu", artist: "Kuban,Żabson"},
    {src: "songs/kyoto.mp3", title: "kyoto", artist: "Kuban,Favst,Zalia"},
    {src: "songs/zapomnę twoje dziary.mp3", title: "zapomnę twoje dziary", artist: "Kuban,Favst"},
    {src: "songs/tagi.mp3", title: "tagi", artist: "Kuban,Favst"},
    {src: "songs/Pokolenie.mp3", title: "Pokolenie", artist: "Kombii"},
];