const songs = [
    {src: "songs/EKSKLUZYWNY_GŁÓD.mp3", title: "EKSKLUZYWNY GŁÓD", artist: "Young igi"},
    {src: "songs/Słup.mp3", title: "Słup", artist: "Białas"},
    {src: "songs/Polsilver.mp3", title: "Polsilver", artist: "PRO8L3M"},
    {src: "songs/Symetryczno-liryczna.mp3", title: "Symetryczno-liryczna", artist: "Enej"},
    {src: "songs/Lili.mp3", title: "Lili", artist: "Enej"},
    {src: "songs/chłopaki jak my.mp3", title: "chłopaki jak my", artist: "Kuban,Favst,Kizo"},
    {src: "songs/Może Będzie lepiej.mp3", title: "Może Będzie lepiej", artist: "Enej"},
    {src: "songs/Skrzydlate ręce.mp3", title: "Skrzydlate ręce", artist: "Kuban,Favst,Kizo"},
    {src: "songs/Nie Chcę Spać.mp3", title: "Nie Chcę Spać", artist: "Enej"},
    {src: "songs/Kamień z Napisem LOVE.mp3", title: "Kamień z Napisem LOVE", artist: "Enej"},
    {src: "songs/Zbudujemy dom.mp3", title: "Zbudujemy dom", artist: "Enej"},
    {src: "songs/Brokeboy.mp3", title: "Brokeboy", artist: "Białas,Szpaku,Tomb"},
    {src: "songs/Uzi.mp3", title: "Uzi", artist: "Białas,Sobel,Deemz"},
    {src: "songs/Na Serio.mp3", title: "Na Serio", artist: "Białas,Lanek,Bedoes 2115"},
    {src: "songs/Nie dla Ciebie.mp3", title: "Nie dla Ciebie", artist: "Solar, Białas, Wac Toja"},
    {src: "songs/GODZILLA FREAKSTYLE.mp3", title: "GODZILLA FREAKSTYLE", artist: "Białas,Lanek"},
    {src: "songs/NIEBIESKI DOM.mp3", title: "NIEBIESKI DOM", artist: "Białas,Lanek"},
    {src: "songs/Intercontinental bajers.mp3", title: "Intercontinental bajers", artist: "Solar, Białas"},
    {src: "songs/Grill u Gawrona.mp3", title: "Grill u Gawrona", artist: "Białas,Lanek"},
    {src: "songs/PRAWDZIWY RAP.mp3", title: "PRAWDZIWY RAP", artist: "Białas,Lanek"},
    {src: "songs/RED BULL 64 BARS.mp3", title: "RED BULL 64 BARS", artist: "Białas,Sobel,Deemz"},
    {src: "songs/Zosia.mp3", title: "Zosia", artist: "Białas"},
    {src: "songs/Idę na plaże.mp3", title: "Idę na plaże", artist: "Video"},
    {src: "songs/Wszystko Jedno.mp3", title: "Wszystko Jedno", artist: "Video"},
    {src: "songs/Street Credit Freestyle.mp3", title: "Street Credit Freestyle", artist: "Białas"},
    {src: "songs/Uratowany przez trap.mp3", title: "Uratowany przez trap", artist: "Białas, SB Maffija"},
    {src: "songs/Ostatni Raz.mp3", title: "Ostatni Raz", artist: "Białas, Gibbs"},
    {src: "songs/Sępy.mp3", title: "Sępy", artist: "Białas,Szpaku"},
    {src: "songs/Jeden żyć.mp3", title: "Jeden żyć", artist: "Białas"},
    {src: "songs/Sweet home.mp3", title: "Sweet home", artist: "Białas, White 2115"},
    {src: "songs/Mamo, sięgam gwiazd.mp3", title: "Mamo, sięgam gwiazd", artist: "Białas"},
    {src: "songs/Smutne miasteczko.mp3", title: "Smutne miasteczko", artist: "Białas,Szpaku,Deemz"},
    {src: "songs/Prawdziwy Król.mp3", title: "Prawdziwy Król", artist: "Białas"},
    {src: "songs/Klękaj przed panem.mp3", title: "Klękaj przed panem", artist: "Białas,Słoń"},
    {src: "songs/Nowy biggie.mp3", title: "Nowy biggie", artist: "Białas"},
    {src: "songs/Blizny na rękach.mp3", title: "Blizny na rękach", artist: "Białas,Lanek"},
    {src: "songs/I poszedł.mp3", title: "I poszedł", artist: "Białas"},
    {src: "songs/Cyka blyat.mp3", title: "Cyka blyat", artist: "Białas,Lanek"},
    {src: "songs/NIE BOJĘ SIĘ DUCHÓW.mp3", title: "NIE BOJĘ SIĘ DUCHÓW", artist: "Białas,Lanek"},
    {src: "songs/Polack.mp3", title: "Polack", artist: "Białas,Lanek"},
    {src: "songs/Witam Cię 2k16.mp3", title: "Witam Cię 2k16", artist: "Białas,Zelo PTP"},
    {src: "songs/How.mp3", title: "How", artist: "Białas"},
];